Repository nail-dp-dev/nail-dp-dev-spring, pull requests merged in 2024-10, with the labels that each got.

#112 [CHORE] : develop-local -> develop
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/common/ProfileInitializer.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/post/TagRequestDto.java
  src/main/java/com/backend/naildp/dto/post/TempPostRequestDto.java
  src/main/java/com/backend/naildp/entity/ArchivePost.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/oauth2/CustomAuthorizationRequestRepository.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/oauth2/jwt/JwtUtil.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/UserRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/UsersProfileRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/main/java/com/backend/naildp/service/PostInfoService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/SecurityFilterTest.java
  src/test/java/com/backend/naildp/controller/ArchiveControllerTest.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/controller/PostLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UserSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/ArchiveServiceTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceUnitTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceUnitTest.java
Labels: chore

#114 [REFACTOR] : 게시물 좋아요 API 수정
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/test/java/com/backend/naildp/service/PostLikeServiceUnitTest.java
Labels: bug

#115 [FIX]: S3 저장 url 변경
  src/main/java/com/backend/naildp/service/S3Service.java
Labels: chore

#117 [REFACTOR] : 팔로우 API 리펙토링
  src/main/java/com/backend/naildp/controller/FollowController.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/service/FollowService.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
Labels: duplicate

#119 [FEAT] : TREND POST 조회 API
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/service/post/NewestPostStrategy.java
  src/main/java/com/backend/naildp/service/post/PostInfoContext.java
  src/main/java/com/backend/naildp/service/post/PostInfoService.java
  src/main/java/com/backend/naildp/service/post/PostStrategy.java
  src/main/java/com/backend/naildp/service/post/TrendPostStrategy.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/PostSearchRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
Labels: enhancement

#120 [FIX] : 프로필 사진 변경 안되는 문제 해결
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
Labels: bug
