Repository nail-dp-dev/nail-dp-dev-spring, pull requests merged in 2024-11, with the labels that each got.

#121 [FEAT]: message 기능 구현
  build.gradle
  src/main/java/com/backend/naildp/common/RoomType.java
  src/main/java/com/backend/naildp/config/JpaAuditingConfiguration.java
  src/main/java/com/backend/naildp/config/MongoConfig.java
  src/main/java/com/backend/naildp/config/RedisConfig.java
  src/main/java/com/backend/naildp/config/chat/KafkaConsumerConfig.java
  src/main/java/com/backend/naildp/config/chat/KafkaProducerConfig.java
  src/main/java/com/backend/naildp/config/chat/KafkaTopicConfig.java
  src/main/java/com/backend/naildp/config/chat/StompHandler.java
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
  src/main/java/com/backend/naildp/config/chat/WebSocketHandshakeInterceptor.java
  src/main/java/com/backend/naildp/controller/chat/ChatRoomController.java
  src/main/java/com/backend/naildp/controller/chat/MessageController.java
  src/main/java/com/backend/naildp/dto/chat/ChatListResponse.java
  src/main/java/com/backend/naildp/dto/chat/ChatListSummaryResponse.java
  src/main/java/com/backend/naildp/dto/chat/ChatMessageDto.java
  src/main/java/com/backend/naildp/dto/chat/ChatRoomRequestDto.java
  src/main/java/com/backend/naildp/dto/chat/ChatUpdateDto.java
  src/main/java/com/backend/naildp/dto/chat/MessageResponseDto.java
  src/main/java/com/backend/naildp/dto/chat/MessageSummaryResponse.java
  src/main/java/com/backend/naildp/dto/chat/RenameChatRoomRequestDto.java
  src/main/java/com/backend/naildp/dto/chat/TempRoomSwitchDto.java
  src/main/java/com/backend/naildp/entity/ChatRoom.java
  src/main/java/com/backend/naildp/entity/ChatRoomUser.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/entity/mongo/ChatMessage.java
  src/main/java/com/backend/naildp/oauth2/jwt/JwtAuthorizationFilter.java
  src/main/java/com/backend/naildp/repository/ChatRoomMapping.java
  src/main/java/com/backend/naildp/repository/ChatRoomRepository.java
  src/main/java/com/backend/naildp/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/backend/naildp/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/ChatRoomUserRepository.java
  src/main/java/com/backend/naildp/repository/UserRepository.java
  src/main/java/com/backend/naildp/repository/UserRepositoryCustom.java
  src/main/java/com/backend/naildp/repository/UserRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/mongo/ChatMessageRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/S3Service.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/main/java/com/backend/naildp/service/chat/ChatRoomService.java
  src/main/java/com/backend/naildp/service/chat/ChatRoomStatusService.java
  src/main/java/com/backend/naildp/service/chat/KafkaConsumerService.java
  src/main/java/com/backend/naildp/service/chat/KafkaProducerService.java
  src/main/java/com/backend/naildp/service/chat/MessageService.java
  src/main/java/com/backend/naildp/service/chat/MessageStatusService.java
  src/main/java/com/backend/naildp/service/chat/SessionService.java
  src/main/resources/static/app.js
  src/main/resources/static/index.html
  src/test/java/com/backend/naildp/service/UserInfoServiceUnitTest.java
Labels: enhancement, chore

#123 [FIX]: ws-stomp 경로 못찾는 문제
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#124 [FIX]: stomp 경로 못찾는 문제 수정
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#125 [FIX]: websocket 경로 허용 안됨
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
Labels: bug

#126 [FIX]: websocket 경로 허용
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
Labels: bug

#127 [FIX]: ws-stomp connection 문제
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#128 [FIX]: ws-stomp connect 문제
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#129 [FIX]: cors오류해결을 위한 websocketConfig allowedOrigin 명시적으로 작성
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#130 [FIX]: cors 오류 해결을 위한 websocketConfig allowedOrigins 명시적 작성
  src/main/java/com/backend/naildp/config/chat/WebSocketConfig.java
Labels: bug

#131 [FIX]: kafka groupId를 서버마다 독립적으로 설정
  src/main/java/com/backend/naildp/config/chat/KafkaConsumerConfig.java
Labels: bug

#132 [FIX]: kafka groupId를 서버마다 독립적으로 설정
  src/main/java/com/backend/naildp/config/chat/KafkaConsumerConfig.java
Labels: bug

#133 [FEAT] : FORYOU 게시물 조회 API
  .gitignore
  build.gradle
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/service/post/ForyouPostStrategy.java
  src/main/java/com/backend/naildp/service/post/PostInfoContext.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/ArchiveRepositoryTest.java
  src/test/java/com/backend/naildp/repository/CommentRepositoryTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/ForYouPostTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UserSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: enhancement

#134 [FEAT] : 알림 조회 및 푸시알림 API
  build.gradle
  src/main/java/com/backend/naildp/common/NotificationType.java
  src/main/java/com/backend/naildp/config/AsyncConfig.java
  src/main/java/com/backend/naildp/config/RedisConfig.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/NotificationController.java
  src/main/java/com/backend/naildp/controller/NotifyController.java
  src/main/java/com/backend/naildp/controller/UserSettingController.java
  src/main/java/com/backend/naildp/dto/notification/NotificationResponseDto.java
  src/main/java/com/backend/naildp/dto/notification/PushNotificationDto.java
  src/main/java/com/backend/naildp/dto/notification/UnreadNotificationIdDto.java
  src/main/java/com/backend/naildp/dto/setting/NotificationSettingResponseDto.java
  src/main/java/com/backend/naildp/entity/Comment.java
  src/main/java/com/backend/naildp/entity/Notification.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/entity/UserNotification.java
  src/main/java/com/backend/naildp/exception/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/repository/EmitterRepository.java
  src/main/java/com/backend/naildp/repository/NotificationCustomRepository.java
  src/main/java/com/backend/naildp/repository/NotificationRepository.java
  src/main/java/com/backend/naildp/repository/NotificationRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/UserNotificationRepository.java
  src/main/java/com/backend/naildp/service/CommentLikeService.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/main/java/com/backend/naildp/service/FollowService.java
  src/main/java/com/backend/naildp/service/NotificationService.java
  src/main/java/com/backend/naildp/service/NotifyEventHandler.java
  src/main/java/com/backend/naildp/service/NotifyService.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/main/java/com/backend/naildp/service/RedisMessageService.java
  src/main/java/com/backend/naildp/service/RedisSubscriber.java
  src/main/java/com/backend/naildp/service/SseEmitterService.java
  src/main/java/com/backend/naildp/service/UserNotificationService.java
  src/test/java/com/backend/naildp/repository/NotificationRepositoryImplTest.java
  src/test/java/com/backend/naildp/repository/NotificationRepositoryTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
Labels: enhancement

#135 [FEAT] : for you 게시물 조회 API, 알림 API
  .gitignore
  build.gradle
  src/main/java/com/backend/naildp/common/NotificationType.java
  src/main/java/com/backend/naildp/config/AsyncConfig.java
  src/main/java/com/backend/naildp/config/RedisConfig.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/controller/NotificationController.java
  src/main/java/com/backend/naildp/controller/NotifyController.java
  src/main/java/com/backend/naildp/controller/UserSettingController.java
  src/main/java/com/backend/naildp/dto/notification/NotificationResponseDto.java
  src/main/java/com/backend/naildp/dto/notification/PushNotificationDto.java
  src/main/java/com/backend/naildp/dto/notification/UnreadNotificationIdDto.java
  src/main/java/com/backend/naildp/dto/setting/NotificationSettingResponseDto.java
  src/main/java/com/backend/naildp/entity/Comment.java
  src/main/java/com/backend/naildp/entity/Notification.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/entity/UserNotification.java
  src/main/java/com/backend/naildp/exception/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/EmitterRepository.java
  src/main/java/com/backend/naildp/repository/NotificationCustomRepository.java
  src/main/java/com/backend/naildp/repository/NotificationRepository.java
  src/main/java/com/backend/naildp/repository/NotificationRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/repository/UserNotificationRepository.java
  src/main/java/com/backend/naildp/service/CommentLikeService.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/main/java/com/backend/naildp/service/FollowService.java
  src/main/java/com/backend/naildp/service/NotificationService.java
  src/main/java/com/backend/naildp/service/NotifyEventHandler.java
  src/main/java/com/backend/naildp/service/NotifyService.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/main/java/com/backend/naildp/service/RedisMessageService.java
  src/main/java/com/backend/naildp/service/RedisSubscriber.java
  src/main/java/com/backend/naildp/service/SseEmitterService.java
  src/main/java/com/backend/naildp/service/UserNotificationService.java
  src/main/java/com/backend/naildp/service/post/ForyouPostStrategy.java
  src/main/java/com/backend/naildp/service/post/PostInfoContext.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/ArchiveRepositoryTest.java
  src/test/java/com/backend/naildp/repository/CommentRepositoryTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/ForYouPostTest.java
  src/test/java/com/backend/naildp/repository/NotificationRepositoryImplTest.java
  src/test/java/com/backend/naildp/repository/NotificationRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UserSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: enhancement

#136 [TEST] : foryou 게시물 조회 테스트 작성
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/service/post/ForyouPostStrategy.java
  src/main/java/com/backend/naildp/service/post/PostInfoService.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
  src/test/java/com/backend/naildp/service/post/ForyouPostStrategyTest.java
Labels: bug

#137 [FIX] : Foryou게시물 조회 수정
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/test/java/com/backend/naildp/service/post/ForyouPostStrategyTest.java
Labels: bug

#138 [REFACTOR]: 댓글 좋아요 API 리펙토링
  src/main/java/com/backend/naildp/service/CommentLikeService.java
  src/main/java/com/backend/naildp/service/NotificationManager.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceTest.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceUnitTest.java
Labels: documentation

#139 [REFACOTR] : 댓글 좋아요 API 에서 게시물 검증 로직 분리
  src/main/java/com/backend/naildp/service/CommentLikeService.java
  src/main/java/com/backend/naildp/service/PostAccessValidator.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceUnitTest.java
Labels: documentation, duplicate

#140 [FEATURE]: 다날 본인인증 로직 추가
  build.gradle
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/ImpCertificationController.java
  src/main/java/com/backend/naildp/controller/SettingLoginController.java
  src/main/java/com/backend/naildp/dto/auth/ImpCertificationRequestDto.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/repository/UserRepository.java
  src/main/java/com/backend/naildp/service/ImpCertificationService.java
  src/main/java/com/backend/naildp/service/SettingLoginService.java
Labels: enhancement

#142 [REFACTOR]: 댓글 생성, 수정, 삭제 리펙토링
  src/main/java/com/backend/naildp/entity/CommentLike.java
  src/main/java/com/backend/naildp/entity/PostLike.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/main/java/com/backend/naildp/service/NotificationManager.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/test/java/com/backend/naildp/repository/ForYouPostTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/service/CommentServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: duplicate, enhancement
