Repository nail-dp-dev/nail-dp-dev-spring, pull requests merged in 2024-07, with the labels that each got.

#14 [FEAT] : 유저 정보 cookie set
  build.gradle
  src/main/java/com/backend/naildp/common/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/common/ApiResponse.java
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/dto/KakaoUserInfoDto.java
  src/main/java/com/backend/naildp/dto/LoginRequestDto.java
  src/main/java/com/backend/naildp/dto/LoginResponseDto.java
  src/main/java/com/backend/naildp/dto/UserInfoResponseDto.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/SocialLogin.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
  src/test/java/com/backend/naildp/SecurityFilterTest.java
Labels: enhancement

#15 fix : requestPart -> requestbody로 변경 #8
  src/main/java/com/backend/naildp/controller/AuthController.java
Labels: bug

#16 [FIX] : 사용자 테이블 약관동의 컬럼 추가 #8
  src/main/java/com/backend/naildp/dto/LoginRequestDto.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
Labels: enhancement

#17 [FIX] : response login type 추가 및 userInfo 쿠키 지우기 #8
  src/main/java/com/backend/naildp/common/ApiResponse.java
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
Labels: enhancement, chore

#18 [CHORE] : CustomException handler 설정 #8
  src/main/java/com/backend/naildp/common/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/common/ApiResponse.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/dto/NicknameRequsetDto.java
  src/main/java/com/backend/naildp/exception/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/exception/ApiResponse.java
  src/main/java/com/backend/naildp/exception/CustomException.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
Labels: chore

#19 [CHORE] : response handler 수정 및 Validation 추가
  build.gradle
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/dto/LoginRequestDto.java
  src/main/java/com/backend/naildp/dto/LoginResponseDto.java
  src/main/java/com/backend/naildp/dto/NicknameRequestDto.java
  src/main/java/com/backend/naildp/dto/PhoneNumberRequestDto.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/exception/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/exception/ApiResponse.java
  src/main/java/com/backend/naildp/exception/CustomException.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/jwt/JwtUtil.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
Labels: chore

#20 [FEAT] : 최신 게시물 조회 API, 게시물 좋아요 API, 게시물 좋아요 취소 API
  build.gradle
  src/main/java/com/backend/naildp/NaildpApplication.java
  src/main/java/com/backend/naildp/config/JpaAuditingConfiguration.java
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/controller/PostLikeController.java
  src/main/java/com/backend/naildp/dto/LoginResponseDto.java
  src/main/java/com/backend/naildp/dto/NicknameRequsetDto.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/entity/Archive.java
  src/main/java/com/backend/naildp/entity/ArchivePost.java
  src/main/java/com/backend/naildp/entity/Photo.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/PostLike.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/repository/UserRepository.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/ArchivePostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: enhancement

#22 [FEAT] : 로그아웃 및 쿠키검증 기능 구현
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/exception/ApiExceptionHandler.java
  src/main/java/com/backend/naildp/exception/ApiResponse.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/exception/TokenNotValidateException.java
  src/main/java/com/backend/naildp/jwt/ErrorResponse.java
  src/main/java/com/backend/naildp/jwt/ExceptionHandlerFilter.java
  src/main/java/com/backend/naildp/jwt/JwtAuthorizationFilter.java
  src/main/java/com/backend/naildp/jwt/JwtUtil.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
Labels: enhancement

#23 [TEST] : auth api 테스트 코드 작성
  build.gradle
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CookieUtilTest.java
Labels: chore

#25 [FEAT] : 좋아요 체크한 게시물 조회 API 구현 및 테스트 코드 작성
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/entity/PostLike.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: enhancement

#26 [DOCS] : PR 템플릿 업로드
  .github/ISSUE_TEMPLATE/pr-템플릿.md
Labels: documentation

#28 [FEAT] : 게시물 작성 api 구현
  build.gradle
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/config/S3Config.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/LoginResponseDto.java
  src/main/java/com/backend/naildp/dto/auth/KakaoUserInfoDto.java
  src/main/java/com/backend/naildp/dto/auth/LoginRequestDto.java
  src/main/java/com/backend/naildp/dto/auth/LoginResponseDto.java
  src/main/java/com/backend/naildp/dto/auth/NicknameRequestDto.java
  src/main/java/com/backend/naildp/dto/auth/PhoneNumberRequestDto.java
  src/main/java/com/backend/naildp/dto/post/PostRequestDto.java
  src/main/java/com/backend/naildp/dto/post/TagRequestDto.java
  src/main/java/com/backend/naildp/entity/Photo.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/Tag.java
  src/main/java/com/backend/naildp/entity/TagPost.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/jwt/JwtAuthenticationFilter.java
  src/main/java/com/backend/naildp/repository/PhotoRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/repository/TagRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/main/java/com/backend/naildp/service/S3Service.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/repository/ArchivePostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CookieUtilTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceUnitTest.java
Labels: enhancement

#29 fix : bug 수정 #24
  src/main/java/com/backend/naildp/service/PostService.java
Labels: enhancement

#30 [REFACTOR] : 최신 게시물 조회 API 리펙토링 및 응답값 변경
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: enhancement, error

#32 [FEAT] : 로그인 유저 정보 조회
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/dto/userInfo/UserInfoResponseDto.java
  src/main/java/com/backend/naildp/entity/Follow.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/ProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: enhancement

#33 [FEAT] : 최신 게시물 조회 API 로직 수정 및 테스트 작성
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: bug, enhancement

#34 [REFACTOR] : 최신 게시물 조회 API 수정 및 테스트 작성
  src/main/java/com/backend/naildp/common/FileExtensionChecker.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: documentation, enhancement

#38 [FIX] : UserProfile, Profile 수정 및 UploadPost 버그 수정
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/UsersProfile.java
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/repository/UsersProfileRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: bug

#39 [Refactor] : 좋아요 게시물 조회 API 리펙토링 및 PostService 분리
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/service/PostInfoService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/ArchivePostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceUnitTest.java
Labels: duplicate, enhancement
