Repository nail-dp-dev/nail-dp-dev-spring, pull requests merged in 2024-08, with the labels that each got.

#44 [FEAT] : 특정 게시물 상세 조회 API
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/dto/post/PostInfoResponse.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/CommentRepository.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/service/PostInfoService.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: enhancement

#46 [FEAT] : 프로필 이미지 crud
  src/main/java/com/backend/naildp/common/ProfileType.java
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/dto/userInfo/ProfileRequestDto.java
  src/main/java/com/backend/naildp/dto/userInfo/UserInfoResponseDto.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/repository/UsersProfileRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: enhancement, chore

#47 [Feat] : 특정 유저 게시물 조회
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/controller/UserPostController.java
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/dto/userInfo/TempSaveResponseDto.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/repository/PostMapping.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/main/java/com/backend/naildp/service/S3Service.java
  src/main/java/com/backend/naildp/service/UserPostService.java
  src/test/java/com/backend/naildp/service/UserPostServiceTest.java
Labels: chore

#48 [FIX] : 테스트 에러 수정
  src/main/java/com/backend/naildp/dto/post/PostRequestDto.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
Labels: bug

#51 [FEATURE] : 댓글 CRUD API
  src/main/java/com/backend/naildp/controller/CommentController.java
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/comment/CommentInfoResponse.java
  src/main/java/com/backend/naildp/dto/comment/CommentRegisterDto.java
  src/main/java/com/backend/naildp/dto/comment/CommentSummaryResponse.java
  src/main/java/com/backend/naildp/entity/Comment.java
  src/main/java/com/backend/naildp/entity/CommentLike.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/repository/CommentRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/repository/CommentRepositoryTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceUnitTest.java
Labels: enhancement

#50 [REFACTOR] : 엔티티 빌더 설정 및 테스트 객체 생성 수정
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/dto/comment/CommentRegisterDto.java
  src/main/java/com/backend/naildp/dto/post/PostInfoResponse.java
  src/main/java/com/backend/naildp/entity/Comment.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/CommentRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/main/java/com/backend/naildp/service/PostInfoService.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
  src/test/java/com/backend/naildp/entity/PostTest.java
  src/test/java/com/backend/naildp/entity/UserTest.java
  src/test/java/com/backend/naildp/repository/ArchivePostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/CommentRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceUnitTest.java
  src/test/java/com/backend/naildp/service/CookieUtilTest.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
  src/test/java/com/backend/naildp/service/UserPostServiceTest.java
Labels: chore

#53 [FEAT] : 게시물 공개 범위 변경 API
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/post/PostBoundaryRequest.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/entity/PostTest.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: enhancement

#56 [FEAT] : 게시물 좋아요 개수 조회 API
  src/main/java/com/backend/naildp/controller/PostLikeController.java
  src/main/java/com/backend/naildp/dto/postLike/PostLikeCountResponse.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/service/PostLikeService.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceUnitTest.java
Labels: enhancement

#57 [FIX] : userPost 오류 수정
  src/main/java/com/backend/naildp/controller/UserPostController.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/UserPostService.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
Labels: bug

#58 [FEAT] : 댓글 좋아요, 좋아요 취소, 좋아요 개수 조회 API
  src/main/java/com/backend/naildp/controller/CommentLikeController.java
  src/main/java/com/backend/naildp/repository/CommentLikeRepository.java
  src/main/java/com/backend/naildp/service/CommentLikeService.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceTest.java
  src/test/java/com/backend/naildp/service/CommentLikeServiceUnitTest.java
Labels: enhancement

#60 [FIX] : 특정 게시물 상세 정보 읽기 API 응답값 수정
  src/main/java/com/backend/naildp/dto/post/PostInfoResponse.java
  src/main/java/com/backend/naildp/entity/PostLike.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: documentation, enhancement

#61 [FIX] : 댓글 조회 응답에 isLiked 필드 추가
  src/main/java/com/backend/naildp/controller/CommentController.java
  src/main/java/com/backend/naildp/dto/comment/CommentInfoResponse.java
  src/main/java/com/backend/naildp/entity/Comment.java
  src/main/java/com/backend/naildp/entity/CommentLike.java
  src/main/java/com/backend/naildp/service/CommentService.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceUnitTest.java
Labels: documentation, enhancement

#62 [FEAT] : 팔로우 / 언팔로우 / 팔로워 수 조회 API
  src/main/java/com/backend/naildp/controller/FollowController.java
  src/main/java/com/backend/naildp/entity/Follow.java
  src/main/java/com/backend/naildp/repository/FollowRepository.java
  src/main/java/com/backend/naildp/service/FollowService.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
Labels: enhancement

#64 [FEAT] : 내 아카이브 페이지 api 구현
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/dto/archive/ArchiveIdRequestDto.java
  src/main/java/com/backend/naildp/dto/archive/ArchiveResponseDto.java
  src/main/java/com/backend/naildp/dto/archive/CreateArchiveRequestDto.java
  src/main/java/com/backend/naildp/dto/archive/FollowArchiveResponseDto.java
  src/main/java/com/backend/naildp/dto/archive/PostIdRequestDto.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/entity/Archive.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/ArchiveMapping.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/ArchiveRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
  src/test/java/com/backend/naildp/service/ArchiveServiceTest.java
  src/test/java/com/backend/naildp/service/GetArchiveServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
Labels: enhancement

#66 [FEAT] 게시물 삭제 api 구현
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/CommentRepository.java
  src/main/java/com/backend/naildp/repository/PhotoRepository.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/service/PostDeletionFacade.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
Labels: enhancement

#68 [FEAT] 다른 유저 정보 조회
  src/main/java/com/backend/naildp/common/ProfileInitializer.java
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/dto/userInfo/UserInfoResponseDto.java
  src/main/java/com/backend/naildp/repository/ProfileRepository.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/service/UserInfoServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceUnitTest.java
Labels: enhancement

#71 [REFACTOR] : 수정 및 삭제 api code 2000 -> 2001로 변경 #70
  src/main/java/com/backend/naildp/controller/CommentController.java
  src/main/java/com/backend/naildp/controller/CommentLikeController.java
  src/main/java/com/backend/naildp/controller/FollowController.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/controller/PostLikeController.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/controller/PostLikeControllerUnitTest.java
Labels: chore

#72 [FEAT]:다른 유저의 아카이브 리스트 조회
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/dto/archive/ArchiveResponseDto.java
  src/main/java/com/backend/naildp/dto/archive/UserArchiveResponseDto.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/repository/ArchiveRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
Labels: enhancement

#74 [FIX] : HomePostResponse에 Boundary 추가
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/test/java/com/backend/naildp/repository/ArchiveRepositoryTest.java
Labels: chore

#75 [FEAT] : 게시물 공유, 공유 수 조회 API 구현
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/entity/Post.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: enhancement

#76 [FEAT] : 특정 게시물 상세 조회 API 응답에 Boundary 추가
  src/main/java/com/backend/naildp/dto/post/PostInfoResponse.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: chore

#78 [FIX] : tag LowerCase로만 저장되도록 변경
  src/main/java/com/backend/naildp/service/PostService.java
Labels: chore

#79 [FIX] : archive 조회 버그 수정
  src/main/java/com/backend/naildp/dto/home/HomePostResponse.java
  src/main/java/com/backend/naildp/dto/home/PostSummaryResponse.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/PostLikeRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
  src/main/java/com/backend/naildp/service/UserPostService.java
Labels: bug

#80 [FIX] : createArchive return값 id, ArchivePostSummaryResponse 추가
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/dto/archive/ArchivePostSummaryResponse.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
Labels: bug

#81 [FEAT] : 검색 API
  build.gradle
  src/main/java/com/backend/naildp/controller/SearchController.java
  src/main/java/com/backend/naildp/dto/search/RelatedTagResponse.java
  src/main/java/com/backend/naildp/dto/search/SearchUserResponse.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/TagPostSearchRepository.java
  src/main/java/com/backend/naildp/repository/UserRepository.java
  src/main/java/com/backend/naildp/repository/UserRepositoryCustom.java
  src/main/java/com/backend/naildp/repository/UserRepositoryImpl.java
  src/main/java/com/backend/naildp/service/SearchService.java
  src/test/java/com/backend/naildp/config/QueryDslTestConfig.java
  src/test/java/com/backend/naildp/repository/PostSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UserSearchRepositoryTest.java
Labels: enhancement
