Repository nail-dp-dev/nail-dp-dev-spring, pull requests merged in 2024-09, with the labels that each got.

#82 [FIX] : 게시물 검색 API 수정
  src/main/java/com/backend/naildp/controller/SearchController.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
Labels: bug

#83 [FIX] : User 클래스 archiveCount 쿼리 소문자로 변경
  src/main/java/com/backend/naildp/entity/User.java
Labels: bug

#84 [FIX] : 팔로우 api 수정
  src/main/java/com/backend/naildp/controller/FollowController.java
  src/main/java/com/backend/naildp/service/FollowService.java
Labels: bug

#85 [FIX] : 게시물 검색 API 수정
  src/main/java/com/backend/naildp/controller/SearchController.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/service/SearchService.java
Labels: bug

#86 [FEAT] : 검색 API 여러 태그로 검색되도록 변경
  src/main/java/com/backend/naildp/controller/SearchController.java
  src/main/java/com/backend/naildp/repository/PostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/PostSearchRepository.java
  src/main/java/com/backend/naildp/repository/TagPostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/TagPostSearchRepository.java
  src/main/java/com/backend/naildp/service/SearchService.java
  src/test/java/com/backend/naildp/repository/PostSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
Labels: enhancement

#87 [FEAT] : google, naver 로그인 적용
  build.gradle
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/common/ProviderType.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/dto/auth/KakaoUserInfoDto.java
  src/main/java/com/backend/naildp/dto/auth/SocialUserInfoDto.java
  src/main/java/com/backend/naildp/entity/SocialLogin.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/exception/SignUpRequiredException.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/oauth2/GoogleOAuth2UserInfo.java
  src/main/java/com/backend/naildp/oauth2/KakaoOAuth2UserInfo.java
  src/main/java/com/backend/naildp/oauth2/NaverOAuth2UserInfo.java
  src/main/java/com/backend/naildp/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/backend/naildp/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/backend/naildp/oauth2/OAuth2UserInfo.java
  src/main/java/com/backend/naildp/repository/SocialLoginRepository.java
  src/main/java/com/backend/naildp/security/UserDetailsImpl.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/KakaoService.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/repository/ArchivePostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/FollowRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostLikeRepositoryTest.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/CookieUtilTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceTest.java
  src/test/java/com/backend/naildp/service/PostLikeServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
Labels: enhancement

#89 [FEAT] : 게시물 저장해제, 게시물이 포함된 아카이브 조회
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/dto/archive/ArchivePostSummaryResponse.java
  src/main/java/com/backend/naildp/dto/archive/UnsaveRequestDto.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/ArchiveRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
  src/main/java/com/backend/naildp/validation/ValidationGroups.java
  src/main/java/com/backend/naildp/validation/ValidationSequence.java
  src/test/java/com/backend/naildp/repository/ArchiveRepositoryTest.java
  src/test/java/com/backend/naildp/service/ArchiveServiceTest.java
Labels: enhancement

#90 [FEAT] : 특정 게시물 읽기 API 저장유무 필드 추가
  src/main/java/com/backend/naildp/dto/post/PostInfoResponse.java
  src/main/java/com/backend/naildp/service/PostService.java
  src/test/java/com/backend/naildp/entity/UserTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
Labels: enhancement

#91 [FIX] : 내 아카이브 내 좋아요 조회 오류 수정
  src/main/java/com/backend/naildp/repository/PostRepository.java
Labels: bug

#92 [FEAT] : 리프레시 토큰 추가
  build.gradle
  src/main/java/com/backend/naildp/config/RedisConfig.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/controller/UserPostController.java
  src/main/java/com/backend/naildp/entity/User.java
  src/main/java/com/backend/naildp/exception/ErrorCode.java
  src/main/java/com/backend/naildp/jwt/JwtAuthorizationFilter.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/oauth2/handler/CustomAccessDeniedHandler.java
  src/main/java/com/backend/naildp/oauth2/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/naildp/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/backend/naildp/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/backend/naildp/oauth2/impl/UserDetailsImpl.java
  src/main/java/com/backend/naildp/oauth2/impl/UserDetailsServiceImpl.java
  src/main/java/com/backend/naildp/oauth2/jwt/ErrorResponse.java
  src/main/java/com/backend/naildp/oauth2/jwt/ExceptionHandlerFilter.java
  src/main/java/com/backend/naildp/oauth2/jwt/JwtAuthenticationFilter.java
  src/main/java/com/backend/naildp/oauth2/jwt/JwtAuthorizationFilter.java
  src/main/java/com/backend/naildp/oauth2/jwt/JwtUtil.java
  src/main/java/com/backend/naildp/oauth2/jwt/RedisUtil.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/test/java/com/backend/naildp/JwtUtilTest.java
  src/test/java/com/backend/naildp/SecurityFilterTest.java
  src/test/java/com/backend/naildp/controller/ArchiveControllerTest.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/CommentServiceTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
Labels: enhancement

#95 [CONF] : cors url 추가
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
Labels: chore

#102 [CONF] build setting
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/gradle.yml
  Dockerfile
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/controller/ArchiveController.java
  src/main/java/com/backend/naildp/controller/AuthController.java
  src/main/java/com/backend/naildp/controller/CommentController.java
  src/main/java/com/backend/naildp/controller/CommentLikeController.java
  src/main/java/com/backend/naildp/controller/FollowController.java
  src/main/java/com/backend/naildp/controller/HomeController.java
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/controller/PostLikeController.java
  src/main/java/com/backend/naildp/controller/SearchController.java
  src/main/java/com/backend/naildp/controller/UserInfoController.java
  src/main/java/com/backend/naildp/controller/UserPostController.java
  src/main/java/com/backend/naildp/oauth2/CustomAuthorizationRequestRepository.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/backend/naildp/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: chore

#104 [FIX] : 댓글 작성 API 수정 #43
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/gradle.yml
  src/main/java/com/backend/naildp/service/CommentService.java
Labels: bug

#103 [FEAT] tag validate 메서드 생성
  src/main/java/com/backend/naildp/controller/PostController.java
  src/main/java/com/backend/naildp/dto/post/TagRequestDto.java
  src/main/java/com/backend/naildp/dto/post/TempPostRequestDto.java
  src/main/java/com/backend/naildp/service/PostService.java
Labels: duplicate

#106 [FIX] : 최신 게시물 조회 시 팔로우 공개 게시물 조회 안되는 문제 해결
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/PostInfoService.java
  src/test/java/com/backend/naildp/repository/PostRepositoryTest.java
  src/test/java/com/backend/naildp/service/PostInfoServiceUnitTest.java
Labels: bug

#107 [FIX] : profile 수정 시 간혹 변경 안되는 문제
  src/main/java/com/backend/naildp/common/CookieUtil.java
  src/main/java/com/backend/naildp/common/ProfileInitializer.java
  src/main/java/com/backend/naildp/config/WebSecurityConfig.java
  src/main/java/com/backend/naildp/entity/Profile.java
  src/main/java/com/backend/naildp/oauth2/CustomAuthorizationRequestRepository.java
  src/main/java/com/backend/naildp/oauth2/CustomOAuth2UserService.java
  src/main/java/com/backend/naildp/repository/UsersProfileRepository.java
  src/main/java/com/backend/naildp/service/AuthService.java
  src/main/java/com/backend/naildp/service/UserInfoService.java
  src/test/java/com/backend/naildp/repository/UsersProfileRepositoryTest.java
  src/test/java/com/backend/naildp/service/AuthServiceTest.java
  src/test/java/com/backend/naildp/service/PostServiceTest.java
  src/test/java/com/backend/naildp/service/UserInfoServiceUnitTest.java
Labels: bug

#108 [FIX] : Controller Test 오류 수정
  src/test/java/com/backend/naildp/controller/ArchiveControllerTest.java
  src/test/java/com/backend/naildp/controller/AuthControllerTest.java
  src/test/java/com/backend/naildp/controller/CommentControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/HomeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/PostCreateControllerTest.java
  src/test/java/com/backend/naildp/controller/PostLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/controller/UserInfoControllerTest.java
Labels: bug

#109 [FEAT] : 사용자 검색 API, 연관 태그 검색 API 수정
  src/main/java/com/backend/naildp/repository/TagPostRepositoryImpl.java
  src/main/java/com/backend/naildp/repository/UserRepositoryImpl.java
  src/test/java/com/backend/naildp/repository/TagSearchRepositoryTest.java
  src/test/java/com/backend/naildp/repository/UserSearchRepositoryTest.java
Labels: enhancement

#110 [FIX] : archivePost 조회순서 변경, archive 저장 해제 시 thumbnail 변경
  src/main/java/com/backend/naildp/entity/ArchivePost.java
  src/main/java/com/backend/naildp/repository/ArchivePostRepository.java
  src/main/java/com/backend/naildp/repository/PostRepository.java
  src/main/java/com/backend/naildp/service/ArchiveService.java
  src/test/java/com/backend/naildp/SecurityFilterTest.java
  src/test/java/com/backend/naildp/controller/CommentLikeControllerUnitTest.java
  src/test/java/com/backend/naildp/service/ArchiveServiceTest.java
  src/test/java/com/backend/naildp/service/FollowServiceUnitTest.java
  src/test/java/com/backend/naildp/service/PostCreateServiceTest.java
Labels: bug
